In [4]:
import numpy
n = numpy.arange(27)

In [10]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
import cv2

In [14]:
im_g = cv2.imread("smallgray.png",0) #second param means whether image is grayscale or RGB
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [16]:
im_rgb = cv2.imread("smallgray.png",1) #second param means whether image is grayscale or RGB
im_rgb

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [19]:
cv2.imwrite("newsmallgray.png",im_rgb)

True

In [33]:
#indexing array
print(im_g[0,3])
print(im_g[0:2,3:4])
#transpose
print(im_g.T)
#list all
for i in im_g.flat:
    print(i)

121
[[121]
 [255]]
[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]
187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [40]:
#stack arrays horizontally or vertically - params must be in tuple or array
imhs = numpy.hstack([im_g,im_g])
imvs = numpy.vstack([im_g,im_g])
print(imhs)
print(imvs)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]
[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [42]:
#split arrays horizontally or vertically
imhsp = numpy.hsplit(im_g,5)
imvsp = numpy.vsplit(im_g,3)
print(imhsp)
print(imvsp)

[array([[187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182]], dtype=uint8)]
[array([[187, 158, 104, 121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182]], dtype=uint8)]
